name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest discover -s src/tests

    - name: Build Docker image
      run: |
        docker build -t kavishka12/crypto-price-service:latest ./src/crypto_price_service
        docker build -t kavishka12/transaction-service:latest ./src/transaction_service
        docker build -t kavishka12/account-service:latest ./src/account_service

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker images
      run: |
        docker push kavishka12/crypto-price-service:latest
        docker push kavishka12/transaction-service:latest
        docker push kavishka12/account-service:latest

    - name: Deploy
      if: success()
      run: |
        # Your deployment commands here
        echo "Deployment step not configured"
